wix/react-native-notifications

package.json

RN version strict restriction lifted

---

react-native-notifications.podspec

This adds a Podspec file, it will make cocoapods users happy :)

Add Podspec

---

.travis.yml
RNNotifications/RNNotifications.h
RNNotifications/RNNotifications.m

based on #25 but rebase to latest master code
Fixes #24

RN 0.40 support

---

index.ios.js

Fix flow errors from #54 .  Verify there are no flow errors with this fix.

Fix flow errors

---

README.md
RNNotifications/RNNotifications.m
index.ios.js
notification.ios.js
test/index.ios.spec.js
test/notification.ios.spec.js

In iOS 10, a new UNUserNotification class was introduced, this class has a method which get and remove the notifications from notification center.
Fix #34

Integrare UNUserNotification

---

README.md
RNNotifications/RNNotifications.m
index.ios.js

Add an option to suppress notification sound. Allows for in-app
notification mute

Add silent option to iOS localNotification

---

android/build.gradle
android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

I've followed a lot of code fixes on this lib and on others, but this is what fixed for me.
Closes #243

[FIX] Android 8

---

android/src/main/java/com/wix/reactnativenotifications/Defs.java
android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
docs/notificationsEvents.md
index.android.js

Added listener that will only receive notifications that happen in foreground

Foreground listener

---

android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

Remove verify notification, Closes #296

---

RNNotifications/RCTConvert+RNNotifications.h

Fix iOS build

---

.circleci/config.yml
.travis.yml
README.md
e2e/Notifications.test.js
example/ios/NotificationsExampleApp.xcodeproj/xcshareddata/xcschemes/NotificationsExampleApp_release.xcscheme
package.json
scripts/install.android.sh
scripts/install.ios.sh
scripts/install.sh
scripts/test.js

Migrated CI from travis to circleCI and added the following steps:
• Android unit tests
• iOS unit tests
• iOS e2e tests using detox

Migration to circleCI

---

android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

Reverts wix/react-native-notifications#349

Revert "Remove verify notification, Closes #296"

---

docs/general-api.md

Under the title "registerRemoteNotifications", I made the following change. 
replaced: RemoteNotificationsRegistered
with: registerRemoteNotificationsRegistered

referencing registerRemoteNotificationsRegistered

---

lib/android/app/src/reactNative59/java/com/wix/reactnativenotifications/NotificationManagerCompatFacade.java

This causes build on ReactNative59 to fail.

Fix wrong import

---

docs/subscription.md

Fix docs code on how to request permissions

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

This PR is for fix issue: #494

Fix foreground notification icon color issue

---

docs/notifications-events.md

Fixed typo in docs: notifications-events.md

Fix typo in event documentation

---

lib/src/DTO/Notification.ts
lib/src/DTO/NotificationFactory.ts

fix crash when ios local notification is received in foreground

---

lib/ios/RNPushKitEventHandler.m
lib/src/Notifications.ts
lib/src/adapters/CompletionCallbackWrapper.ts
lib/src/events/EventsRegistryIOS.test.ts
lib/src/events/EventsRegistryIOS.ts

The missing parts of the earlier pull request.

Pushkit completion

---

lib/src/interfaces/NotificationCategory.ts

This is what I could gleam from the documentation.

Fix incorrect types for NotificationActions

---

example/NotificationsExampleApp.tsx
example/index.js

continue #812. need index.js as the starting point for iOS

back to index js

---

lib/android/app/build.gradle
lib/android/build.gradle

bump android sdk version to 31 in lib

---

example/NotificationsExampleApp.tsx
example/ios/Podfile.lock
website/docs/api/general-events.md

Get opened notification from get initial notification

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java
lib/android/app/src/test/java/com/wix/reactnativenotifications/core/notification/PushNotificationTest.java
website/docs/api/general-events.md

android: do not display data-only PN

---

website/docs/docs/subscription.md

This fixes a minor typo I came across

Fix typo in docs of subscription

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java

as said here: https://github.com/wix/react-native-notifications/issues/828#issuecomment-1050254561

latest notification data in getInitialNotification

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java

trigger notificationOpened from killed state

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

fix-tests-from-#967

---

lib/android/app/build.gradle
lib/android/build.gradle

upgrade-android-33
