wix/react-native-notifications

index.ios.js

- A lot of the `let`s aren't reassigned. To avoid accidental reassignment of the reference, we should change them to a `const`.
- The `Map`s should be a `let` as well since they aren't reassigned and can still be updated via all the usual methods attached to them.
- Slightly updated the method `removeEventListener` to get rid of the unneeded return.

Change unneeded lets to consts

---

README.md
RNNotifications/RNNotifications.h
RNNotifications/RNNotifications.m
index.ios.js
test/index.ios.spec.js

With the current implementation there is no way of telling whether or not the push registration was successful. This PR exposes the native `didFailToRegisterForRemoteNotificationsWithError` to JS by means of a newly introduced `remoteNotificationsRegistrationFailed` event. This allows for gracefully handling failure cases.

Expose registration failure event

---

README.md
RNNotifications/RNNotifications.m
index.ios.js
test/index.ios.spec.js

Add a checkPermissions function allowing the app to determine what
notification permissions the user has granted. The function returns a
promise resolving to an object with permission info.

Add iOS checkPermissions

---

README.md
RNNotifications/RNNotifications.m
index.ios.js
notification.ios.js
test/index.ios.spec.js
test/notification.ios.spec.js

This is an extension of #50; that PR adds support for enumerating/dismissing delivered notifications
by ID, but UserNotifications notifications and UILocalNotification notifications have a different set of IDs (a notification created using UILocalNotification will have an ID that does not match the
notification's ID in the UserNotifications world and hence cannot be used to dismiss that notification). This PR creates the notifications using UserNotifications if the user is on iOS 10 so that the IDs returned by `localNotification` can be used to dismiss the notifications after they are delivered.

Use UserNotifications to create/dismiss local notifications

---

RNNotifications/RNNotifications.h
RNNotifications/RNNotifications.m

This allows users to integrate with services that don't use Apple's APN ID as their primary device identifier, namely Firebase Cloud Messaging. With this change it's possible to consistently utilise FCM for both iOS and Android.

Accept string device tokens

---

android/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java

[`createJSModules` is now not required on Android](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8) from RN 0.47. I actually can't build an app on RN 0.47 without removing this method. This change is backwards compatible.

Remove createJSModules @overide marker - RN 0.47 compatibility

---

index.ios.js

This fixes Flow errors relating to `Duplicate module provider`: 
```bash
$ flow
Error: node_modules/react-native-notifications/index.ios.js:0
RNNotifications. Duplicate module provider
current provider. See: ios/node_modules/react-native-notifications/index.ios.js:0
```
[`@providesModule` is not meant to be used by systems outside of Facebook.](https://github.com/facebook/flow/issues/2648#issuecomment-254883663)
This Haste module is never used by the library, and only interferes with usage in Haste-based systems.

Remove @providesModule

---

RNNotifications/RNNotifications.m

Adjust the setting of the `openedLocalNotification` from `launchOptions` to use the `userInfo` from the `UILocalNotification` if it exists instead of the `UILocalNotification` itself. This prevents `null` from being passed through to the `IOSNotification` constructor which causes the crash described in #83 when an app is opened fresh versus being resumed from the background.
When comparing to how remote notifications are handled, `UIApplicationLaunchOptionsRemoteNotificationKey` returns "an NSDictionary containing the payload of the remote notification" where `UIApplicationLaunchOptionsLocalNotificationKey` returns a `UILocalNotification` as mentioned so using the `userInfo` dictionary is the most appropriate option to allow the rest of the notification handling flow to function.

iOS opening Local Notification crash fix

---

RNNotifications/RNNotifications.m
docs/advancedIos.md
index.ios.js
test/index.ios.spec.js

This PR adds a method for getting the current badge count, which could be useful for incrementing / decrementing the badge count.

Added method for getting the current iOS badge count

---

RNNotifications/RNNotifications.m

for the first time. refs #268 
The `didReceiveRemoteNotification` method checks for the current app state which will be active when queue processing takes place and hence it wrongly emits the notification to JS as foreground. However at the exact time when the user opened the notification, the app was at the background hence this is a background notification by definition.
In other words, conceptually determining if the notification is background or foreground should NOT be based on the time it was consumed from the queue but on the time it was received. Practically, if it was queued, then the app must have been in the background ==> background notification.

fix background PN is received as foreground

---

RNNotifications/RNNRouter.h
RNNotifications/RNNRouter.m
RNNotifications/RNNotifications.h
RNNotifications/RNNotifications.m
RNNotifications/RNNotifications.xcodeproj/project.pbxproj
RNNotifications/RNNotifications.xcodeproj/project.xcworkspace/contents.xcworkspacedata
RNNotifications/RNNotifications.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
docs/installation.md
example/ios/NotificationsExampleApp/AppDelegate.h
example/ios/NotificationsExampleApp/AppDelegate.m
example/package.json
index.ios.js
package.json
test/index.ios.spec.js

replacing the deprecated Notifications API (iOS 4.0–10.0).
Other than replacing the old deprecated API, While looking at the current implementation, I realized that `NSNotification` were used to allow programers to call methods of the native module's instance (which is initialised by bridge somewhere, so I don't have it) from the native, I think that this is an abuse of `NSNotification`.
What I plan to do is to use a singleton as a router `RNNRouter` ; in the module's constructor, instead of listening to `NSNotification`, I'll assign the module as the router's singleton delegate, this will allow me to observe the calls to the instance, and also prevent confusions (someone else is listening to the same notification), also it gives me the power to monitor all the calls to the instance …

[WIP] iOS deprecated API replacement

---

.github/main.workflow
.grenrc.js
package.json
scripts/release.js

Resolves and categorise PR's using labels and generates `CHANGELOG.gren.md` upon each release.

Autogenerate changelog using github-release-notes

---

android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
android/app/src/reactNative59/java/com/wix/reactnativenotifications/NotificationManagerCompatFacade.java
docs/installation.md

At the moment, the package has an error under RN59 where the wrong annotation is being imported. This is causing my build to break and can only assume many others who have not upgraded to 60.
The package also has an issue where the app icon is a white square. This is because the notification builder is setting the small icon to be the same as the app icon and in most cases the app icon does not follow the same design requirements as the notification icon (White and Transparent only). My change here should be a non breaking change as it still supports the app icon being imported if a notification icon is not defined/provided.

Fixing white square icon and annotation error

---

lib/ios/RNBridgeModule.m
lib/ios/RNCommandsHandler.h
lib/ios/RNCommandsHandler.m

I was getting a similar error message to https://github.com/wix/react-native-notifications/issues/429 but for `getBadgeCount()`. Turns out we need to use resolve and reject blocks as it is expected to return a promise.

Use resolve reject for getBadgeCount

---

docs/installation-android.md

Issue #461 
I got the following error message. 
package com.wix.reactnativenotifications does not exist
I fixed it by making the following changes. 
1. Added the following line to Project/app/build.gradle
implementation project(':react-native-notifications')
2. Changed the line in MainApplication.java FROM: 
new RNNotificationsPackage(MainApplication.this) 
TO: 
packages.add(new RNNotificationsPackage(MainApplication.this));

package wix.reactnativenotifications does not exist

---

react-native.config.js

Currently, auto-link failing for android.
`react-native config` outputs followings.
```json
"react-native-notifications": {
"root": "path_to/node_modules/react-native-notifications",
"name": "react-native-notifications",
"platforms": {
"ios": {
// ...
},
"android": null
},
}
```
This commit fix this

Fix auto-link for android

---

lib/ios/RNBridgeModule.m
lib/ios/RNCommandsHandler.h
lib/ios/RNCommandsHandler.m
lib/ios/RNNotificationCenter.h

Used resolve and reject blocks as it is expected to return a promise in `getDeliveredNotifications`. Solves #429

Use resolve reject for getDeliveredNotifications

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsModule.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/AppLaunchHelper.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ProxyService.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ReactAppLifecycleFacade.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/fcm/FcmInstanceIdListenerService.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/fcm/FcmToken.java

- We need to make sure that no log statements goes production since this
library deals with sensitive push device token.
- The method used is how android source code uses to log in debug
and remove logs in production.
- Tested in my app
Comment if you want me to make any changes in this PR

Wrap all log statements inside debug flag

---

lib/android/app/src/main/AndroidManifest.xml

According to Google GCM to FCM Migration guide, the removed lines of code are no longer required. And could create duplicate notifications.
https://developers.google.com/cloud-messaging/android/android-migrate-fcm
I have run the library in my local project after removing those lines, it works fine.
I had already sent a PR which got closed due to inactivity by bot.
https://github.com/wix/react-native-notifications/pull/294
I hope at least this PR gets merged.
Please comment if you want me to make any changes in this PR.
Thanks

Remove obsolete elements from manifest

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java

This PR fixes:
* Empty foreground notification content if your notification payload has `title` and `body` files under `notification` field rather than `data`.
* Get `undefined` initial notification data if your notification payload has `title` and `body` files under `notification` field rather than `data`.
Details of issue and notification payloads: https://github.com/wix/react-native-notifications/issues/456#issuecomment-585559278
Related issues: #456 , #492

Fix initial notification data lost issue and empty foreground notification issue

---

docs/android-api.md

This PR is a follow up with documentation of the [previous PR](https://github.com/wix/react-native-notifications/pull/535) which added support for android's channels.

Docs for setNotificationChannel

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notificationdrawer/PushNotificationsDrawer.java
lib/android/app/src/test/java/com/wix/reactnativenotifications/core/notification/PushNotificationTest.java
lib/android/app/src/test/java/com/wix/reactnativenotifications/core/notificationdrawer/PushNotificationsDrawerTest.java

It fixes a problem of removing all notification from a notification drawer when a single notification is opened.

fix: do not clear other notifications on open a notification

---

README.md

Added latest npm version tag and changed the links to this repo instead of `react-native-navigation`
closes https://github.com/wix/react-native-notifications/issues/568

Fixed shield.io badge to link rn-notifications in README

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java

Background notifications can still contain a title key, and this is erroneously not showing notifications that it should be.
This fixes getInitialNotification() on Android.

Remove check for title in background firebase notifications

---

lib/ios/RNBridgeModule.m
lib/ios/RNCommandsHandler.h
lib/ios/RNCommandsHandler.m
lib/ios/RNNotificationCenter.h
lib/ios/RNNotificationCenter.m

This PR fixes crash on iOS when canceling local notifications.
`cancelLocalNotification` on iOS expected notificationId string which was wrong for the reason that it receives number from the JS side.

Fix cancelLocalNotification crash on iOS

---

README.md

fixed link to API docs in README

docs: fix link to API docs in README

---

website/docs/localNotifications.md

Added note that scheduled notifications are not implemented on android yet to avoid confusion. As you can see in issue https://github.com/wix/react-native-notifications/issues/484 this is not quite clear from the docs.

Added note about scheduled notifications not implemented on android yet

---

lib/ios/RNBridgeModule.m

I was facing the same issue described by https://github.com/wix/react-native-notifications/issues/184 (specifically when calling `ios.setBadgeCount()`). I'm not a native developer so I don't fully understand what this PR is doing but am just resurrecting the fix proposed by @LeoNatan. It fixes the problems for me when built locally!

Ensure react-native-notifications calls go out on main queue.

---

example/index.js
example/ios/NotificationsExampleApp/AppDelegate.m
lib/ios/RCTConvert+RNNotifications.h
lib/ios/RCTConvert+RNNotifications.m
lib/ios/RNBridgeModule.m
lib/ios/RNCommandsHandler.h
lib/ios/RNCommandsHandler.m
lib/ios/RNEventEmitter.h
lib/ios/RNEventEmitter.m
lib/ios/RNNotificationEventHandler.h
lib/ios/RNNotificationEventHandler.m
lib/ios/RNNotificationParser.h
lib/ios/RNNotificationParser.m
lib/ios/RNNotifications.h
lib/ios/RNNotifications.m
lib/ios/RNNotificationsStore.h
lib/ios/RNNotificationsStore.m
lib/src/adapters/CompletionCallbackWrapper.ts
lib/src/adapters/NativeCommandsSender.ts
lib/src/adapters/NativeEventsReceiver.ts
lib/src/events/EventsRegistry.test.ts
lib/src/events/EventsRegistry.ts
lib/src/index.ts
lib/src/interfaces/NotificationCompletion.ts

We still need to use `application:didReceiveRemoteNotification:fetchCompletionHandler:` to handle silent notifications / background updates according to [this](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc).
I am adding this helper so I can simply call `RNNotifications:didReceiveBackgroundNotification:withCompletionHandler` in my `application:didReceiveRemoteNotification:fetchCompletionHandler:`.

Add event and handler for iOS background notification

---

lib/src/adapters/CompletionCallbackWrapper.ts
lib/src/adapters/NativeEventsReceiver.ts
lib/src/events/EventsRegistry.test.ts

`EventsRegistry.registerNotificationOpened` registers a `callback` that expects a `response: NotificationResponse` object as the first parameter. In the registered callback, we can expect `response.notificaiton` to be the notification opened.
However, `NativeEventsReceiver.registerNotificationOpened` wants a `callback` that expects a `notification: Notification` object instead. So we are passing back `notification` as the `response` which will cause the callback code to get `undefined` as the notification.
This fixes the mismatch to supply both the notification and the action to the registered callback.

Fix EventsRegistry.registerNotificationOpened typing

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/fcm/FcmToken.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/fcm/IFcmTokenListenerApplication.java

Sometimes we need to use the FCM token, sync with server and more.
Today the token is sent to the JS, that prevents us from making custom native logic that deals with FCM token.
Changes done as small as possible, it is optional, Instance of Application class can implement the interface in order to receive the token itself to the native side.

FCM Token Listener application

---

website/docs/installation-android.md

Remove adding the package to the list of packages. This is done automatically because of auto-linking. The following section is not required anymore. 
@Override
protected List<ReactPackage> getPackages() {
@SuppressWarnings("UnnecessaryLocalVariable")
List<ReactPackage> packages = new PackageList(this).getPackages();
// ... 
// Add the following line: 
packages.add(new RNNotificationsPackage(MainApplication.this)); 
return packages;
}

Remove adding the package to the list of packages.

---

lib/android/app/src/main/AndroidManifest.xml
lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsModule.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/fcm/FcmInstanceIdRefreshHandlerService.java

- Changes the mechanism by which the library fetches the FCM token in the background.
In newer Android versions (8+), background applications cannot start `IntentService`'s. Using the notifications library in these newer Android versions will result in a lot of exceptions of the type `java.lang.IllegalStateException`. Sample stack trace:
```
java.lang.IllegalStateException: 
at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1522)
at android.app.ContextImpl.startService (ContextImpl.java:1478)
at android.content.ContextWrapper.startService (ContextWrapper.java:650)
at com.wix.reactnativenotifications.RNNotificationsModule.startFcmIntentService (RNNotificationsModule.java:135)
at com.wix.reactnativenotifications.RNNotificationsModule.initialize (RNNotificationsModule.java:50) …
```

[Bugfix][Android] Use JobServiceIntent to fetch the FCM token in the background

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/Defs.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

When app in the background the js thread is not granted to be running to making sure it is only sent when the app is in FG.

notifyReceivedToJS only when app is visible

---

lib/ios/RNNotifications.m

I can't see a reason why `RNNotifications.m` should have its own instance of `RNNotificationsStore` so I'm certain it's a bug. That  was what caused the notifications to not be shown the first time

Fixes #627 - First foreground notification is not visible

---

example/ios/NotificationsExampleAppTests/RNNotificationsStoreTests.m
lib/ios/RNNotificationsStore.m

On iOS 14 built with Xcode 12 fixes a crash mentioning that completionHandler should run on the main thread

action completeHandler must run on main thread

---

lib/ios/RNCommandsHandler.m

There is a problem on iOS we encountered in RN application. 
Steps to reproduce: 
- App is dead
- Notification received (with deep link to some screen in app) 
- User opened the notification and navigated to some place in app 
- User performed some actions, which cause app to reload from scratch 
- App is loading from scratch ( initial notification is still there )
- Notification handler takes the initial notification again 
- User navigated to some place in app again
Expected behaviour: 
Initial notification should be cleared.

[BugFix][iOS] Cleaning up initial notification after resolve

---

lib/ios/RNNotificationCenter.m

In iOS, `@(YES)` is converted as `[NSNumber numberWithBool:]`, generating a `__NSCFBoolean` instance.
While `@(1 == 1)` is converted as `[NSNumber numberWithInt:]`, generating a `__NSCFNumber` instance.
And RN converter treat this differently. The first one becomes bool value, and the second one becomes numberic value.
This PR makes sure the return value from native side will match type declaration in ts file `lib/src/interfaces/NotificationPermissions.ts`:
```
export interface NotificationPermissions {
badge: boolean;
alert: boolean;
sound: boolean;
}
```

Fix boolean type when converting to js

---

lib/src/Notifications.ts

Makes the id optional when posting a local notification.

Make notification id optional fixes #703

---

example/index.js
lib/src/Notifications.ts
lib/src/NotificationsIOS.ts
website/docs/api/ios-api.md

I realized that #740 could break builds that uses `Notifications.ios.registerRemoteNotifications` although in docs it was `Notifications.ios.requestPermissions`. Then I decided to return to the original name and to fix the doc to be coherent to this.

return to ios.registerRemoteNotifications name

---

example/index.js
lib/ios/RNNotificationCenter.m
lib/ios/RNNotificationsTests/Integration/RNCommandsHandlerIntegrationTest.m
lib/src/adapters/NativeCommandsSender.ts
website/docs/api/ios-api.md

Adding `Provisional` option to `ios.registerRemoteNotifications`.
See apple [docs](https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications) for reference.

Provisional option in iOS registeration

---

lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts
package.json

In order to solve the [security vulnerability](https://github.com/advisories/GHSA-35jh-r3h4-6jhm) lodash should be upgraded
I removed the import of lodash when it's not needed

upgrade lodash to 4.17.21

---

example/ios/NotificationsExampleAppTests/RNNotificationsStoreTests.m
lib/ios/RNNotificationsStore.m

Finishing #692 . As it said there, completion handler should run in main thread.
Should fix #746

finish run completion handler in main thread

---

example/ios/Podfile.lock
lib/ios/RNNotificationCenter.m
lib/ios/RNNotifications.h
lib/ios/RNNotifications.m
website/docs/docs/subscription.md

Continuing #752:
returning whether `provisional` is enabled in `Notifications.ios.checkPermissions()`
Added here #731 changes in order to enhance releasing

expose provisional state

---

lib/ios/RNNotificationCenter.m

continuing #733, we want to register to remote notifications on provisional approve.

resiter remote on provisional approve

---

example/index.js
lib/ios/RNNotificationCenter.m
lib/src/commands/Commands.test.ts
lib/src/interfaces/NotificationPermissions.ts

Add `norificationCenter` and `lockScreen` to permissions status

FEAT: ios add permissions to check permissions

---

lib/android/app/src/main/AndroidManifest.xml

It's required since Android 12 and makes apps targeting Android 12 or higher fail to build.

fix: Add missing `android:exported` to `service`

---

lib/android/app/build.gradle

`minSdkVersion` and `compileSdkVersion` are already defined in react-native templates and all projects have both. other RN libraries also use the names for reading the configs. so there is no need to define new names. because it makes developers duplicate the values in their root project just for react-native-notification

used common ext names exported in root project

---

CODEOWNERS
lib/android/app/build.gradle
lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

revert android to api 30

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

fix initial notification from killed

---

website/docs/api/general-events.md

after many many questions about `handle registerNotificationReceivedBackground on IOS` I decided to emphasize the iOS guide which is very important to understand the lot of restrictions in order to get this event
Issues for example: #836 #834

emphasize NotificationReceivedBackground ios guide

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
lib/android/app/src/test/java/com/wix/reactnativenotifications/core/notification/PushNotificationTest.java

The default channel shouldn't be built if there's already another channel, never mind if the existing one is the default or some other channel.

create default channel only when no existing channel

---

lib/ios/RNEventEmitter.h
lib/ios/RNEventEmitter.m
lib/ios/RNNotificationCenter.m
lib/src/adapters/NativeEventsReceiver.ts
lib/src/events/EventsRegistry.ts
website/docs/api/general-events.md

On iOS, calling `requestPermissions` causes a permission dialog to appear.
Pressing OK in this dialog will eventually emit a `registerRemoteNotificationsRegistered` or `registerRemoteNotificationsFailed` event.
However, there's no event emitted if the user chooses "Don't Allow", so if the implementor is attempting to do something in their app depending on which action has been taken, they are unable to do so.
This work exposes a new event called: `remoteNotificationsRegistrationDenied` that is emitted when `requestAuthorizationWithOptions` has been executed without error but with `granted` set to 'NO'.
Related:
- https://github.com/wix/react-native-notifications/issues/669#issuecomment-1069338103
- https://github.com/wix/react-native-notifications/issues/811

Exposes new event: remoteNotificationsRegistrationDenied

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsModule.java
lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ReactAppLifecycleFacade.java

In order to fix #835 we changed the clear operation to occur after the arguments' extraction.
also changed deprecated `hasActiveCatalystInstance` to `hasActiveReactInstance`

FIX #835: null mNotification

---

lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ReactAppLifecycleFacade.java

Fix #867 
Although hasActiveCatalystInstance is [deprecated](https://github.com/facebook/react-native/blob/09a21f0f3790d42e766d865fd3eb8b1d04a847f7/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L189), devs are still using old versions of RN so we brought it back within a `try` block

FIX 867: add deprecated hasActiveCatalystInstance for old RN

---

react-native.config.js

Fixes #881 
Removed deprecated parameter from react-native.config.js, causing autolinking to fail from react-native/cli v8

fix: remove deprecated config

---

lib/android/app/build.gradle

Fix #975 
https://github.com/wix/react-native-notifications/issues/975
Replace deprecated method setEnabled by required.set()
Use [getRequired()](https://docs.gradle.org/7.3/javadoc/org/gradle/api/reporting/Report.html#getRequired--).set() instead.

Fix android build for RN 0.72
